### PR TITLE
Upgrade `arxiv` dependency to 1.4.2

### LINKED ISSUE #8: Randomness in arxiv API requests
The underlying `arxiv` [package](https://github.com/lukasschwab/arxiv.py/issues/43) had an issue with unreliable results ([#43](https://github.com/lukasschwab/arxiv.py/issues/43)).

Fortunately, this was fixed in the recent [1.0.0 release](https://github.com/lukasschwab/arxiv.py/releases/tag/1.0.0) but here we still depend on the old 0.5.3.

Task: Bump dependency to 1.0.1 and refactor arxiv related code.

### PR DESCRIPTION
**Pull request by lukasschwab**
## Changes

Fix #8 : Pins `arxiv==1.4.1`. Uses `vars()` to convert `arxiv.Result`s to `dict`s for processing.

Updates `arxiv_field_mapper` and `process_fields` accordingly:

+ `(arxiv.Result).journal_reference` is now `(arxiv.Result).journal_ref`.
+ `(arxiv.Result).date` is now a `datetime`; it needs formatting, but not conversion.
+ `(arxiv.Result).authors` is now a list of `arxiv.Author` objects; these are converted to a string.

### Testing

I confirmed that the default fields are processed appropriately for an example paper. The processed dict returned by `get_arxiv_papers`:

```python
{
  'date': '2018-02-20',
  'title': 'Fault Detection Effectiveness of Source Test Case Generation Strategies for Metamorphic Testing',
  'authors': 'Prashanta Saha, Upulee Kanewala',
  'abstract': 'Metamorphic testing is a well known approach to tackle the oracle problem in\nsoftware testing. This technique requires the use of source test cases that\nserve as seeds for the generation of follow-up test cases. Systematic design of\ntest cases is crucial for the test quality. Thus, source test case generation\nstrategy can make a big impact on the fault detection effectiveness of\nmetamorphic testing. Most of the previous studies on metamorphic testing have\nused either random test data or existing test cases as source test cases. There\nhas been limited research done on systematic source test case generation for\nmetamorphic testing. This paper provides a comprehensive evaluation on the\nimpact of source test case generation techniques on the fault finding\neffectiveness of metamorphic testing. We evaluated the effectiveness of line\ncoverage, branch coverage, weak mutation and random test generation strategies\nfor source test case generation. The experiments are conducted with 77 methods\nfrom 4 open source code repositories. Our results show that by systematically\ncreating source test cases, we can significantly increase the fault finding\neffectiveness of metamorphic testing. Further, in this paper we introduce a\nsimple metamorphic testing tool called "METtester" that we use to conduct\nmetamorphic testing on these methods.',
  'journal': '',
  'doi': None
}
```

I also did some light integration testing:

```pycon
>>> from paperscraper.arxiv import get_and_dump_arxiv_papers
>>> query=["relativistic", "strophotron"]
>>> get_and_dump_arxiv_papers(query, output_filepath='rs.jsonl')
```

Which yields the following file:

```
{'date': '2016-12-13', 'title': 'Electron Dynamics in Relativistic Strophotron', 'authors': 'Karen Ivanyan', 'abstract': 'Relativistic strophotron is a system in which fast electrons move along a\npotential trough produced by quadrupole electric lenses. Equations of motion in\nthe strophotron field are investigated and electron trajectories are found. It\nis shown, that electrons are harmonically oscillating in transverse direction\nand do complex motion in longitudinal direction.', 'journal': '', 'doi': None}
{'date': '2016-12-22', 'title': 'Spontaneous Radiation in Relativistic Strophotron', 'authors': 'I. V. Dovgan', 'abstract': 'Spectral intensity of spontaneous radiation is calculated in relativistic\nstrophotron. It is shown, that it in the strophotron is given by a\nsuperposition of contributions from emission at different (odd) harmonics of\nthe main resonance frequency . The main resonance frequency is shown to depend\non the initial conditions of the electron, and in particular on its initial\ntransversal coordinate .', 'journal': '', 'doi': None}
{'date': '2021-08-08', 'title': 'An electron as a wave packet in the relativistic strophotron fel', 'authors': 'M. Hnatic, P. Kopcansky, K. B. Oganesyan', 'abstract': 'We study the initial distribution of electrons in relativistic strophotron\nFEL over vibrational levels determined by the expansion coefficients. We show\nthe quantity of the vibrational level can be expressed in terms of the initial\nparameters of the electron beam.', 'journal': '', 'doi': None}
{'date': '2016-12-30', 'title': 'The emitted energy in RS', 'authors': 'I. V. Dovgan', 'abstract': 'The emitted energy of electrons is calculated in relativistic strophotron. It\nis shown, that it is superposition of amplification at harmonics of main\nresonance frequency of the system.', 'journal': '', 'doi': None}
{'date': '2016-12-15', 'title': 'Quadrupole lenses scheme for RS FEL', 'authors': 'K. V. Ivanyan', 'abstract': 'The scheme with quadrupole lenses is presented for realization relativistic\nstrophotron type Free electron laser. Equations of motion are solved and\ntrajectories are found. It is shown, that movement of electrons in presented\nscheme is stable in both transverse directions.', 'journal': '', 'doi': None}
{'date': '2017-01-07', 'title': 'The Gain in RS', 'authors': 'I. V. Dovgan', 'abstract': 'The calculated linear gain in relativistic strophotron is averaged over\nelectron distribution. It is shown, that after averaging resonance peaks remain\nin amplification spectrum. The nonresonant background gives only negligibly\nsmall contribution to the gain.', 'journal': '', 'doi': None}
{'date': '2016-12-27', 'title': 'Averaging of Spontaneous Radiation in Relativistic Strophotron', 'authors': 'I. V. Dovgan', 'abstract': 'The main resonance frequency is shown to depend on the initial conditions of\nthe electron, and in particular on its initial transversal coordinate xo. This\ndependence is shown to give rise to a very strong inhomogeneous broadening of\nthe spectral lines. The broadening can become large enough for the spectral\nlines to overlap with each other. The spectral intensity of a spontaneous\nemission is averaged over xo. The averaged spectral intensity is shown to have\nonly a very weakly expressed resonance structure.', 'journal': '', 'doi': None}
```

## Notes

**May break non-default usage of `get_arxiv_papers`:** available field names may have changed, and search/client options may have changed.

`vars(r: arxiv.Result)` exposes the following fields:

```pycon
>>> vars(paper).keys()
dict_keys(['entry_id', 'updated', 'published', 'title', 'authors', 'summary', 'comment', 'journal_ref', 'doi', 'primary_category', 'categories', 'links', 'pdf_url', '_raw'])
```

A few more things to consider in review:

+ `arxiv>=1.0.0` specifies search and client options separately. Perhaps these should be separate parameters to `get_and_dump_arxiv_papers`; happy to chat about how the package can enable that (e.g. by specifying some `arxiv.ClientOptions`/`arxiv.SearchOptions` types).
    This PR uses the default client.

+ This change to `process_fields` converts `(arxiv.Result).authors` into a single string of names (see [example above](#Testing)).
    A list of strings may be more appropriate––happy to make that change!

+ I don't think the `if kwargs.get('iterative', False)` condition is useful: it makes this function strictly less efficient.

Hope this is helpful! I spotted the reference to #8 on https://github.com/lukasschwab/arxiv.py/issues/43.

### CODE REVIEW

**Comment by jannisborn** [comment]
Hi @lukasschwab,
Thanks for the excellent work, much appreciated!! I'm more than happy with this PR overall, a few small things remain to be solved before we can merge.

Regarding your notes:
- I agree on the `if kwargs.get('iterative', False)` condition. It seems that you deprecated the `iterative` before `1.4.1` and therefore this condition is harmful (passing `iterative` arg to `arxiv.Search` raises `TypeError`. I removed it in d4343e4
- Having a list of authors instead of a single string with `,` separating the authors seems more natural but might necessitate some downstream changes in the postprocessing and for consistency with the other scrapers (medRxiv, biorXiv, PubMed) I'd prefer to keep this as is.
- specifying `arxiv.ClientOptions` vs. `arxiv.SearchOptions` would be useful, but currently I dont see how this can be specified via `arxiv.Search` as `Search.results` just seems to query `arxiv.Client` without the option to pass down arguments (I believe this because of [this](https://github.com/lukasschwab/arxiv.py/blob/455fb7c90f157c9adc2caa775a5839bf70bb4959/arxiv/arxiv.py#L476)). Lmk if I got this wrong, would be happy to integrate those options if it can be done easily.

**Tests**:
I was able to reproduce your tests 👍🏼 
While the unreliability results seems clearly resolved with the `arxiv` version bump, keywords with larger search volumes are still challenging. I used the example from https://github.com/lukasschwab/arxiv.py/issues/43 and for queries like `quantum` or `'quantum' + 'machine learning'`  and I consistently obtain:

```
arxiv.arxiv.UnexpectedEmptyPageError: Page of results was unexpectedly empty (http://export.arxiv.org/api/query?search_query=all%3Aquantum+AND+all%3Amachine+learning&id_list=&sortBy=relevance&sortOrder=descending&start=3287&max_results=100)
```

What's the recommended workaround here? I understand the error is raised upon exhaustion of retries, so should users rather raise the number of retries? Decrease the `page_size`? Increase the `delay_seconds`? For `paperscraper`, it'd make sense to add the best configuration as default so that users dont have to bother with the specifics of the `arxiv` package. Any thoughts on this? 

Other minor things I did:
- Relaxing the arxiv dependency (`>=1.4.1` instead of `==0.5.3`), also in the `setup.py`
- Bumped package version to `0.1.0` (currently we're at `0.4.0`) upon merging this PR.

**Comment by lukasschwab** [comment]
> specifying `arxiv.ClientOptions` vs. `arxiv.SearchOptions` would be useful, but currently I dont see how this can be specified via `arxiv.Search` as Search.results just seems to query `arxiv.Client` without the option to pass down arguments (I believe this because of [this](https://github.com/lukasschwab/arxiv.py/blob/455fb7c90f157c9adc2caa775a5839bf70bb4959/arxiv/arxiv.py#L476)). Lmk if I got this wrong, would be happy to integrate those options if it can be done easily.

You're right about `(arxiv.Search).results()`!

If you want to make client options user-specifiable, you could change `get_arxiv_papers` to [define a custom client](https://github.com/lukasschwab/arxiv.py#client); something like

```python
def get_arxiv_papers(query, fields, max_results, search_options, client_options):
  client = arxiv.Client(**client_options)
  search = arxiv.Search(query=query, max_results=max_results, **search_options)
  results = client.results(search)
```

> What's the recommended workaround [for `UnexpectedEmptyPageError`s]? I understand the error is raised upon exhaustion of retries, so should users rather raise the number of retries? Decrease the page_size? Increase the delay_seconds? For paperscraper, it'd make sense to add the best configuration as default so that users dont have to bother with the specifics of the arxiv package. Any thoughts on this?

I wish I could recommend a definite fix. This seems to be instability on arXiv's part; since I don't work for arXiv, I don't know the root cause. [I emailed the API Google Group in April](https://groups.google.com/g/arxiv-api/c/8u84_mLjTYQ/m/j3_fUocLCwAJ), but got no explanation.

The default client's `page_size` and `delay_seconds` are pretty gentle (100 results and 3 seconds). I suppose there are *so many* pages of `quantum` results that some page is eventually interrupted by instability.

My best recommendation: use a custom client and increase the number of retries from 3 to 10.

I can also reopen, update, and merge https://github.com/lukasschwab/arxiv.py/pull/53; this'll make retries slower, but perhaps make them more effective.

**Review by jannisborn — APPROVED** [review]

**Comment by jannisborn** [comment]
Thx for the rapid reply. Followed your suggestion to separate `Search` from `Client`. Speed is of secondary importance for paperscraper so I defaulted the retries to 10.

It's annoying that arXiv is unresponsive to these issues... Sleeping between retries seems a good idea, did you play a bit with the API whether it is beneficial (might make sense to monitor it systematically before going straight to a full implementation). 

Regarding bulk access, I'm not familiar with OAI-PMH either and it's probably a bit beyond the scope of this repo.

Thanks again very much for the proactivity and improvements! I think we're ready to merge this 🚀

**Comment by lukasschwab** [comment]
@jannisborn I just released 1.4.2, which includes https://github.com/lukasschwab/arxiv.py/pull/53. Pinning 1.4.2 might get you better performance for really large scrapes, since it enforces `delay_seconds` between retries.

Cheers!

**Pull request merged**
